---
- name: Ensure unzip is installed
  apt: name=unzip state=present

- name: Download nexus OSS artifact
  get_url: url={{ nexus_artifact_url }} dest=/tmp/{{ nexus_artifact }}

- name: Decompress nexus OSS artifact
  unarchive: src=/tmp/{{ nexus_artifact }} dest={{ nexus_install_dir|dirname }} owner={{ nexus_user }} group={{ nexus_group }} copy=no
  notify: Restart nexus

- name: Create symlink to nexus installation directory 
  file: src={{ nexus_install_dir }} dest={{ nexus_home_dir }} owner={{ nexus_user }} group={{ nexus_group }} state=link

- name: Create nexus service startup script
  command: cp {{ nexus_home_dir }}/bin/nexus /etc/init.d/nexus

- name: Update NEXUS_HOME environment variable in startup script
  lineinfile: dest=/etc/init.d/nexus regexp='^NEXUS_HOME=' line='NEXUS_HOME="{{ nexus_home_dir }}"'

- name: Update RUN_AS_USER environment variable in startup script
  lineinfile: dest=/etc/init.d/nexus regexp='^#RUN_AS_USER=' line='RUN_AS_USER="{{ nexus_user }}"'

- name: Update PIDDIR environment variable in startup script
  lineinfile: dest=/etc/init.d/nexus regexp='^#PIDDIR=' line='PIDDIR="{{ nexus_pid_dir }}"'

- name: Ensure nexus startup script has correct permissions
  file: path=/etc/init.d/nexus owner=root group=root mode=0755 state=file

- name: Enable nexus service
  service: name=nexus enabled=yes

- name: Start nexus
  service: name=nexus state=started
